POST http://localhost:5000/ HTTP/1.1
Content-Type: application/json

{
    "name": "Olivie",
    "weight": 1.0,
    "ingredients": ["potatoes", "chicken", "pea", "eggs", "cucumbers"],
    "sauce": "mayonnaise",
    "dietType": "none",
    "spicy": false,
    "expired": "2023-02-21"
}